spring:
  resources:
    static-locations: classpath:/static/
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: cn.zjiali.blog.entity
logging:
  level:
    cn.zjiali.blog.mapper: debug
